#ifndef __QFM_SDK_VERSION_H__
#define __QFM_SDK_VERSION_H__

#define QFM_SDK_VERSION_INFO
#define QFM_SDK_VERSION_MAJOR 0
#define QFM_SDK_VERSION_MINOR 1
#define QFM_SDK_VERSION_REVISION 3
#define QFM_SDK_FILE_VERSION 0,1,3
#define QFM_SDK_PRODUCT_VERSION 0,1,3
#define QFM_SDK_FILE_VERSION_STR "0.1.3"


#endif
